language: node_js
node_js:
  - '8'

cache: yarn

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn && yarn bootstrap

script: yarn build && yarn test:ci && yarn docs

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
